import datetime
from pathlib import Path


def write_latex_metrics(nb_name: str, metrics: dict, output_dir: str | Path, log=None) -> None:
    """Write \\newcommand macros to latex/generated/{nb_name}_metrics.tex.

    The file is overwritten on every run so it always reflects the latest results.
    Keys in metrics become command names; values are written as strings.
    """
    out_path = Path(output_dir) / f'{nb_name}_metrics.tex'
    out_path.parent.mkdir(parents=True, exist_ok=True)

    timestamp = datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    lines = [
        f'% Auto-generated by {nb_name}: DO NOT EDIT MANUALLY',
        f'% Last run: {timestamp}',
        '',
    ]
    for cmd, val in metrics.items():
        cmd_name = cmd.replace('_', '')
        lines.append(f'\\newcommand{{\\{cmd_name}}}{{{val}}}')

    out_path.write_text('\n'.join(lines) + '\n', encoding='utf-8')

    msg = f'LaTeX metrics written: {out_path}'
    if log:
        log.info(msg)
    else:
        print(msg)
