import datetime
from pathlib import Path


def write_latex_metrics(
    nb_name: str,
    metrics: dict,
    output_dir: str | Path,
    log=None,
    key_prefix: str = '',
) -> None:
    """Write \\newcommand macros to latex/generated/{nb_name}_metrics.tex.

    The file is overwritten on every run so it always reflects the latest results.
    Keys in metrics become command names; values are written as strings.

    key_prefix: when non-empty, each key is prefixed with it and its first
    letter is capitalised (e.g. key_prefix='ucihar', key='authAUC' gives
    command \\uciharAuthAUC).  This avoids \\newcommand conflicts when multiple
    dataset tex files are \\input-ted in the same LaTeX document.
    """
    if key_prefix:
        metrics = {
            f'{key_prefix}{k[0].upper()}{k[1:]}': v
            for k, v in metrics.items()
        }

    out_path = Path(output_dir) / f'{nb_name}_metrics.tex'
    out_path.parent.mkdir(parents=True, exist_ok=True)

    timestamp = datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')
    lines = [
        f'% Auto-generated by {nb_name}: DO NOT EDIT MANUALLY',
        f'% Last run: {timestamp}',
        '',
    ]
    for cmd, val in metrics.items():
        cmd_name = cmd.replace('_', '')
        lines.append(f'\\providecommand{{\\{cmd_name}}}{{}}')
        lines.append(f'\\renewcommand{{\\{cmd_name}}}{{{val}}}')

    out_path.write_text('\n'.join(lines) + '\n', encoding='utf-8')

    msg = f'LaTeX metrics written: {out_path}'
    if log:
        log.info(msg)
    else:
        print(msg)
